### ISSUE TITLE
ModuleNotFoundError: No module named 'pyppeteer.jshandle'

### ISSUE THREAD

**Issue by kikikikikinanana** [mcolella14/python_ghost_cursor#3]
Traceback (most recent call last):
  File "C:/Users/aa/PycharmProjects/untitled/complete_exp/test.py", line 25, in <module>
    from pyppeteer_ghost_cursor import createCursor
  File "C:\Users\aa\anaconda3\envs\bot\lib\site-packages\pyppeteer_ghost_cursor-0.1-py3.8.egg\pyppeteer_ghost_cursor\__init__.py", line 3, in <module>
    from pyppeteer_ghost_cursor.spoof import createCursor, get_path as path
  File "C:\Users\aa\anaconda3\envs\bot\lib\site-packages\pyppeteer_ghost_cursor-0.1-py3.8.egg\pyppeteer_ghost_cursor\spoof.py", line 14, in <module>
    from pyppeteer.jshandle import ElementHandle
ModuleNotFoundError: No module named 'pyppeteer.jshandle'

**Comment by mcolella14** [comment]
@JINHYUKJEONG I am almost certain that this is because this repo is built to be compatible with the `pupp-2.1.1` [branch of the pyppeteer repo](https://github.com/pyppeteer/pyppeteer/tree/pup2.1.1). I have this in the README: 

> Currently only for use with the pup2.1.1 branch of pyppeteer. Support for the dev branch will likely be added in the future.

I've been meaning to add support for the `dev` branch (main release) for a while, but other things in my work have taken priority. Sorry about that, I'm hoping I can get some time to work on it this weekend or next week!

**Comment by kikikikikinanana** [comment]
thank you very much

**Comment by mcolella14** [comment]
#5 should fix this.
